walletconnect/Web3modal support
GoodDollar/GoodWeb3-Mono pull request #101
Opened 2023-07-12 15:16 UTC by sirpy

# Description
A wrapper around our web3provider that uses web3modal/wagmi/viem
use the exported useWeb3Modal to open the web3modal
it will wrap viem provider into an ethers web3provider and pass it to our web3provider.

This basically also means that you can use both usedapp and wagmi hooks.

2023-07-23 12:14 UTC, sirpy commented on lint-staged.config.js
> -const { opendirSync } = require("fs");
i've added alternative more succint support eslint.
see master branch

2023-07-23 12:17 UTC, L03TJ3 commented on lint-staged.config.js
> -const { opendirSync } = require("fs");
Ye @johnsmith-gooddollar can explain better as he wrote it

but what I am now missing to see...
it used to run on only changed files

doesn't it now not run on all files in mono?

2023-07-23 12:23 UTC, sirpy commented on lint-staged.config.js
> -const { opendirSync } = require("fs");
for all i know this is the kind of setup everyone uses.
from my testing it seems to run only on staged files.

2023-07-23 12:40 UTC, L03TJ3 approved these changes

2023-07-24 21:39 UTC, L03TJ3 requested changes
storybook is broken

2023-07-25 09:05 UTC, L03TJ3 approved these changes

2023-07-25 11:23 UTC, merged