add hasclaimed hook
GoodDollar/GoodWeb3-Mono pull request #47
Opened 2023-02-20 21:05 UTC by L03TJ3

# Description

Add hook to check if connected account has any claimable UBI on a supported chain

**About**
https://github.com/GoodDollar/GoodProtocolUI/pull/336

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

# Checklist:
- [ ] PR title matches follow: (Feature|Bug|Chore) Task Name
- [ ] My code follows the style guidelines of this project
- [ ] I have followed all the instructions described in the initial task (check Definitions of Done)
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added reference to a related issue in the repository
- [ ] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [ ] @mentions of the person or team responsible for reviewing proposed changes

2023-02-21 16:32 UTC, sirpy commented
@L03TJ3 is this required for the new claim flow?

2023-02-22 02:41 UTC, L03TJ3 commented
@sirpy yes that was the idea. We show that a claim is available on the alternative chain.
I needed something like this to check on both chains if someone has claimed already or not.

You have another suggestion?

2023-02-22 07:04 UTC, sirpy requested changes
1. you are pointing to beta sdk packages. once its ready to merge it should work with the non beta package.
2. i'd change it to useHasClaimed(requiredNetwork)
and in your use case call it twice. useHasClaimed(fuse) useHasClaimed(celo).

2023-02-23 16:12 UTC, johnsmith-gooddollar requested changes

2023-02-23 16:12 UTC, johnsmith-gooddollar commented on packages/sdk-v2/src/sdk/claim/react.ts
> +export const useHasClaimed = (requiredNetwork: keyof typeof SupportedV2Networks) => {
```suggestion
export const useHasClaimed = (requiredNetwork: keyof typeof SupportedV2Networks): boolean => {
```

2023-02-23 20:35 UTC, L03TJ3 commented on packages/sdk-v2/src/sdk/claim/react.ts
> +  };
Well, it first returned two.

But you are right, doesn't make sense to keep the object return now

2023-02-23 20:35 UTC, L03TJ3 commented on packages/sdk-v2/src/sdk/claim/react.ts
> +export const useHasClaimed = (requiredNetwork: keyof typeof SupportedV2Networks) => {
done

2023-02-23 20:39 UTC, merged