add: useContractFunctionWithDefaultFees
GoodDollar/GoodWeb3-Mono pull request #49
Opened 2023-02-21 15:55 UTC by sirpy

# Description
- added new hook that wraps useContractFunction send with fixed gas price
- replaced all useContractFunction usages

About /GoodProtocolUI/issues/335

2023-02-22 14:36 UTC, L03TJ3 requested changes
Works everywhere
except microbridge where for some reason the gaslimit has no set value
(not fully understanding where it goes wrong)

Reproducible with the MicroBridge story in good-design.

2023-02-23 16:17 UTC, johnsmith-gooddollar approved these changes

2023-02-23 20:14 UTC, sirpy commented
@L03TJ3 i've fixed the bridge. i was missing a paramter when encoding the transferAndCall. Usually when you see a gas issue in metamask it is because the dapp failed to estimate the gas because the TX is going to revert.

I've also fixed the bridge to work with correct token decimals. I've started using CurrencyValue more and refactored to simplify the way you handled the tokens decimals. please review and that i'm not breaking anything.

i've also tried to improve references between good-design and sdk-v2 in typescript and tried to fix the types issue by adding custom.d.ts to typeroots in tsconfig

2023-02-27 11:21 UTC, L03TJ3 requested changes

2023-02-27 12:05 UTC, sirpy commented on packages/sdk-v2/src/sdk/constants.ts
> +    new Currency(name, ticker, decimals, {
reverted

2023-02-27 12:54 UTC, L03TJ3 approved these changes

2023-02-27 12:54 UTC, merged