fix first claim flow, update copy's/styles of modals
GoodDollar/GoodWeb3-Mono pull request #52
Opened 2023-02-26 21:53 UTC by L03TJ3

# Description
Updates and adjustments for the first-claim flow modals

About # (link your issue here)
https://github.com/GoodDollar/GoodProtocolUI/issues/317
https://github.com/GoodDollar/GoodProtocolUI/issues/342

2023-02-26 22:03 UTC, L03TJ3 commented
No changes needed on UI side

2023-02-27 20:44 UTC, johnsmith-gooddollar requested changes

2023-02-27 22:35 UTC, L03TJ3 commented on packages/good-design/src/core/images/Image.tsx
> +  return <BaseImage alt="GoodDollar" {...props} source={source} style={imageStyle} w={w} h={h} />;
Verified that it is only used for the claimCarousel
and the original implementation was based on an older ux/ui.

Not the image, but the card itself will be a link URL
so I didn't see the need to keep an onPress handler there

Whenever we need it we can make a variant for it

2023-02-28 19:36 UTC, johnsmith-gooddollar commented on packages/good-design/src/core/images/Image.tsx
> +  return <BaseImage alt="GoodDollar" {...props} source={source} style={imageStyle} w={w} h={h} />;
not needed okay. in goddapp image also hadn't any click interactions as I remember
image it's just an image

just make sure carousel is working (e.g. re-check it with updated package)
thanks

2023-02-28 19:36 UTC, johnsmith-gooddollar approved these changes

2023-03-01 00:35 UTC, merged